-- Auto-generated by pregenerate.py — do not edit by hand.
ADHDQuest_StaticSummaries = {
  ["id:9490"] = "Your cousin-hater cousin was eaten by Blacktalon the Savage in the Great Fissure — kill her and bring back her claws to claim your reward. Turn in the proof to Ikan at the Temple of Telhamat.",
  ["id:9398"] = "Scout Vanura wants you to kill 8 Stonescythe Whelps and 4 Stonescythe Alphas in the Great Fissure to protect the Broken from these predators. The rock flayers are preying on displaced survivors, so thin their numbers at the Temple of Telhamat.",
  ["id:2"] = "Senani Thunderheart wants the Sharptalon claw as proof of your victory. Bring it to Silverwind Refuge.",
  ["id:11"] = "Stormwind wants gnolls near the guard tower and Stone Cairn Lake killed. Collect their painted armbands to prove you handled both packs.",
  ["id:16"] = "Gerard, a farmer, wants spring water to stay hydrated. He’ll trade for it—if you have any on hand.",
  ["id:23"] = "A night elf-trained bear marked with a quarter-crescent emblem, Ursangous, hunted Horde allies. Take its paw to Tarkan at Silverwind Refuge to remove this enemy weapon.",
  ["id:24"] = "Captain Goggath wants the head of the legendary night elf creature Shadumbra to mark the end of the Alliance in Ashenvale. He sees it as a trophy to intimidate and claim victory. You need to bring the head to him at Hellscream’s Watch.",
  ["id:25"] = "Tarkan wants you to stop a twisted elemental that’s causing chaos at Silverwind after the mage who summoned it died in battle. The elemental’s out of control, and no one else can handle it.",
  ["id:35"] = "The Stormwind soldier thinks the murloc rumors might be true and wants you to check with Guard Thomas at the eastern Elwynn bridge, who knows the area's current state. They offer their charger to speed your trip.",
  ["id:37"] = "The quest giver wants to know what happened to Guards Rolf and Malakai, who went to investigate the river and haven’t returned. You need to travel north along the river to find the guards—or what’s left of them—to complete the report.",
  ["id:40"] = "Murlocs are attacking eastern Elwynn Forest and scaring off fish. The NPC wants you to convince Marshal Dughan to send troops there, but he’s focused on gnolls and bandits.",
  ["id:45"] = "Follow webbed footprints east to a Murloc village near Stone Cairn Lake. Investigate the village to uncover what happened to Rolf.",
  ["id:46"] = "Guard Thomas wants you to kill murlocs at Stone Cairn Lake and the forked stream south of Elwynn, collecting 10 torn fins to claim a Stormwind Army bounty. The more you slaughter, the better the reward.",
  ["id:47"] = "NPC wants Gold Dust from kobolds for a good price. Find kobolds in Fargodeep Mine (south) and Jasperlode Mine (northeast) to collect it.",
}